import 'package:covid19_info/models/country.dart';

final List<Country> countries = [
  Country('AFG', 'Afeganistão'),
  Country('ALA', 'Ilhas de Aland'),
  Country('ALB', 'Albânia'),
  Country('DZA', 'Argélia'),
  Country('ASM', 'Samoa Americana'),
  Country('AND', 'Andorra'),
  Country('AGO', 'Angola'),
  Country('AIA', 'Anguila'),
  Country('ATA', 'Antártida'),
  Country('ATG', 'Antígua e Barbuda'),
  Country('ARG', 'Argentina'),
  Country('ARM', 'Armênia'),
  Country('ABW', 'Aruba'),
  Country('AUS', 'Austrália'),
  Country('AUT', 'Áustria'),
  Country('AZE', 'Azerbaijão'),
  Country('BHS', 'Bahamas'),
  Country('BHR', 'Bahrein'),
  Country('BGD', 'Bangladesh'),
  Country('BRB', 'Barbados'),
  Country('BLR', 'Bielorrússia'),
  Country('BEL', 'Bélgica'),
  Country('BLZ', 'Belize'),
  Country('BEN', 'Benin'),
  Country('BMU', 'Bermudas'),
  Country('BTN', 'Butão'),
  Country('BOL', 'Bolívia'),
  Country('BES', 'Bonaire'),
  Country('BIH', 'Bósnia e Herzegovina'),
  Country('BWA', 'Botsuana'),
  Country('BVT', 'Ilha Bouvet'),
  Country('BRA', 'Brasil'),
  Country('IOT', 'Território Britânico do Oceano íÍdico'),
  Country('UMI', 'Ilhas Menores Distantes dos Estados Unidos'),
  Country('VGB', 'Ilhas Virgens Britânicas'),
  Country('VIR', 'Ilhas Virgens Americanas'),
  Country('BRN', 'Brunei'),
  Country('BGR', 'Bulgária'),
  Country('BFA', 'Burkina Faso'),
  Country('BDI', 'Burundi'),
  Country('KHM', 'Camboja'),
  Country('CMR', 'Camarões'),
  Country('CAN', 'Canadá'),
  Country('CPV', 'Cabo Verde'),
  Country('CYM', 'Ilhas Cayman'),
  Country('CAF', 'República Centro-Africana'),
  Country('TCD', 'Chade'),
  Country('CHL', 'Chile'),
  Country('CHN', 'China'),
  Country('CXR', 'Ilha Christmas'),
  Country('CCK', 'Ilhas Cocos'),
  Country('COL', 'Colômbia'),
  Country('COM', 'Comores'),
  Country('COG', 'Congo'),
  Country('COD', 'RD Congo'),
  Country('COK', 'Ilhas Cook'),
  Country('CRI', 'Costa Rica'),
  Country('HRV', 'Croácia'),
  Country('CUB', 'Cuba'),
  Country('CUW', 'Curaçao'),
  Country('CYP', 'Chipre'),
  Country('CZE', 'República Tcheca'),
  Country('DNK', 'Dinamarca'),
  Country('DJI', 'Djibuti'),
  Country('DMA', 'Dominica'),
  Country('DOM', 'República Dominicana'),
  Country('ECU', 'Equador'),
  Country('EGY', 'Egito'),
  Country('SLV', 'El Salvador'),
  Country('GNQ', 'Guiné Equatorial'),
  Country('ERI', 'Eritreia'),
  Country('EST', 'Estônia'),
  Country('ETH', 'Etiópia'),
  Country('FLK', 'Ilhas Malvinas'),
  Country('FRO', 'Ilhas Faroé'),
  Country('FJI', 'Fiji'),
  Country('FIN', 'Finlândia'),
  Country('FRA', 'França'),
  Country('GUF', 'Guiana Francesa'),
  Country('PYF', 'Polinésia Francesa'),
  Country('ATF', 'Terras Austrais e Antárticas Francesas'),
  Country('GAB', 'Gabão'),
  Country('GMB', 'Gâmbia'),
  Country('GEO', 'Geórgia'),
  Country('DEU', 'Alemanha'),
  Country('GHA', 'Gana'),
  Country('GIB', 'Gibraltar'),
  Country('GRC', 'Grécia'),
  Country('GRL', 'Groelândia'),
  Country('GRD', 'Granada'),
  Country('GLP', 'Guadalupe'),
  Country('GUM', 'Guam'),
  Country('GTM', 'Guatemala'),
  Country('GGY', 'Guernsey'),
  Country('GIN', 'Guiné'),
  Country('GNB', 'Guiné-Bissau'),
  Country('GUY', 'Guiana'),
  Country('HTI', 'Haiti'),
  Country('HMD', 'Ilha Heard e Ilhas McDonald'),
  Country('VAT', 'Vaticano'),
  Country('HND', 'Honduras'),
  Country('HKG', 'Hong Kong'),
  Country('HUN', 'Hungria'),
  Country('ISL', 'Islândia'),
  Country('IND', 'Índia'),
  Country('IDN', 'Indonésia'),
  Country('CIV', 'Costa do Marfim'),
  Country('IRN', 'Irã'),
  Country('IRQ', 'Iraque'),
  Country('IRL', 'Irlanda'),
  Country('IMN', 'Ilha de Man'),
  Country('ISR', 'Israel'),
  Country('ITA', 'Itália'),
  Country('JAM', 'Jamaica'),
  Country('JPN', 'Japão'),
  Country('JEY', 'Jersey'),
  Country('JOR', 'Jordânia'),
  Country('KAZ', 'Cazaquistão'),
  Country('KEN', 'Quênia'),
  Country('KIR', 'Kiribati'),
  Country('KWT', 'Kuwait'),
  Country('KGZ', 'Quirguistão'),
  Country('LAO', 'Laos'),
  Country('LVA', 'Letônia'),
  Country('LBN', 'Líbano'),
  Country('LSO', 'Lesoto'),
  Country('LBR', 'Libéria'),
  Country('LBY', 'Líbia'),
  Country('LIE', 'Liechtenstein'),
  Country('LTU', 'Lituânia'),
  Country('LUX', 'Luxemburgo'),
  Country('MAC', 'Macau'),
  Country('MKD', 'Macedônia'),
  Country('MDG', 'Madagascar'),
  Country('MWI', 'Malawi'),
  Country('MYS', 'Malásia'),
  Country('MDV', 'Maldivas'),
  Country('MLI', 'Mali'),
  Country('MLT', 'Malta'),
  Country('MHL', 'Ilhas Marshall'),
  Country('MTQ', 'Martinica'),
  Country('MRT', 'Mauritânia'),
  Country('MUS', 'Maurício'),
  Country('MYT', 'Mayotte'),
  Country('MEX', 'México'),
  Country('FSM', 'Micronésia'),
  Country('MDA', 'Moldávia'),
  Country('MCO', 'Mônaco'),
  Country('MNG', 'Mongólia'),
  Country('MNE', 'Montenegro'),
  Country('MSR', 'Montserrat'),
  Country('MAR', 'Marrocos'),
  Country('MOZ', 'Moçambique'),
  Country('MMR', 'Myanmar'),
  Country('NAM', 'Namíbia'),
  Country('NRU', 'Nauru'),
  Country('NPL', 'Nepal'),
  Country('NLD', 'Holanda'),
  Country('NCL', 'Nova Caledônia'),
  Country('NZL', 'Nova Zelândia'),
  Country('NIC', 'Nicarágua'),
  Country('NER', 'Níger'),
  Country('NGA', 'Nigéria'),
  Country('NIU', 'Niue'),
  Country('NFK', 'Ilha Norfolk'),
  Country('PRK', 'Coreia do Norte'),
  Country('MNP', 'Ilhas Marianas'),
  Country('NOR', 'Noruega'),
  Country('OMN', 'Omã'),
  Country('PAK', 'Paquistão'),
  Country('PLW', 'Palau'),
  Country('PSE', 'Palestina'),
  Country('PAN', 'Panamá'),
  Country('PNG', 'Papua Nova Guiné'),
  Country('PRY', 'Paraguai'),
  Country('PER', 'Peru'),
  Country('PHL', 'Filipinas'),
  Country('PCN', 'Ilhas Pitcairn'),
  Country('POL', 'Polônia'),
  Country('PRT', 'Portugal'),
  Country('PRI', 'Porto Rico'),
  Country('QAT', 'Catar'),
  Country('KOS', 'Kosovo'),
  Country('REU', 'Reunião'),
  Country('ROU', 'Romênia'),
  Country('RUS', 'Rússia'),
  Country('RWA', 'Ruanda'),
  Country('BLM', 'São Bartolomeu'),
  Country('SHN', 'Santa Helena'),
  Country('KNA', 'São Cristóvão e Neves'),
  Country('LCA', 'Santa Lúcia'),
  Country('MAF', 'Saint Martin'),
  Country('SPM', 'Saint-Pierre e Miquelon'),
  Country('VCT', 'São Vicente e Granadinas'),
  Country('WSM', 'Samoa'),
  Country('SMR', 'San Marino'),
  Country('STP', 'São Tomé e Príncipe'),
  Country('SAU', 'Arábia Saudita'),
  Country('SEN', 'Senegal'),
  Country('SRB', 'Sérvia'),
  Country('SYC', 'Seicheles'),
  Country('SLE', 'Serra Leoa'),
  Country('SGP', 'Singapura'),
  Country('SXM', 'Sint Maarten'),
  Country('SVK', 'Eslováquia'),
  Country('SVN', 'Eslovênia'),
  Country('SLB', 'Ilhas Salomão'),
  Country('SOM', 'Somália'),
  Country('ZAF', 'República Sul-Africana'),
  Country('SGS', 'Ilhas Geórgias do Sul e Sandwich do Sul'),
  Country('KOR', 'Coreia do Sul'),
  Country('SSD', 'Sudão do Sul'),
  Country('ESP', 'Espanha'),
  Country('LKA', 'Sri Lanka'),
  Country('SDN', 'Sudão'),
  Country('SUR', 'Suriname'),
  Country('SJM', 'Svalbard'),
  Country('SWZ', 'Suazilândia'),
  Country('SWE', 'Suécia'),
  Country('CHE', 'Suíça'),
  Country('SYR', 'Síria'),
  Country('TWN', 'Taiwan'),
  Country('TJK', 'Tajiquistão'),
  Country('TZA', 'Tanzânia'),
  Country('THA', 'Tailândia'),
  Country('TLS', 'Timor Leste'),
  Country('TGO', 'Togo'),
  Country('TKL', 'Tokelau'),
  Country('TON', 'Tonga'),
  Country('TTO', 'Trinidad e Tobago'),
  Country('TUN', 'Tunísia'),
  Country('TUR', 'Turquia'),
  Country('TKM', 'Turcomenistão'),
  Country('TCA', 'Ilhas Turcas e Caicos'),
  Country('TUV', 'Tuvalu'),
  Country('UGA', 'Uganda'),
  Country('UKR', 'Ucrânia'),
  Country('ARE', 'Emirados árabes Unidos'),
  Country('GBR', 'Reino Unido'),
  Country('USA', 'Estados Unidos'),
  Country('URY', 'Uruguai'),
  Country('UZB', 'Uzbequistão'),
  Country('VUT', 'Vanuatu'),
  Country('VEN', 'Venezuela'),
  Country('VNM', 'Vietnã'),
  Country('WLF', 'Wallis e Futuna'),
  Country('ESH', 'Saara Ocidental'),
  Country('YEM', 'Iêmen'),
  Country('ZMB', 'Zâmbia'),
  Country('ZWE', 'Zimbabwe')
];
